[package]
name = "meta-maxim/luau-types"
version = "1.0.5"
license = "MIT"
authors = ["Maxim Borsch <@Meta_Maxim>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]